[package]
name = "crush"
version = "0.1.0"
authors = ["axel <liljencrantz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1"
lazy_static = "1.4.0"
rustyline = "5.0.3"
map_in_place = "0.1.0"
psutil = "1.0.0"
users = "0.9.1"
dirs = "1.0.5"
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
crossbeam = "0.7"
time = "0.1.40"
