[package]
name = "crush"
version = "0.1.0"
authors = ["axel <liljencrantz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1"
lazy_static = "1.4.0"
rustyline = "5.0.3"
either = "1.5.3"
map_in_place = "0.1.0"
psutil = "1.0.0"
users = "0.9.1"
