[package]
name = "crush"
version = "0.1.0"
authors = ["Axel Liljencrantz <liljencrantz@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "A command line shell that is also a powerful and modern programming language"
readme = "README.md"
repository = "https://github.com/liljencrantz/crush"
license = "MIT"

[build-dependencies.prost-build]
version = "0.6.1"

[build-dependencies.lalrpop]
version = "0.18.1"
features = ["lexer"]

[dependencies]
lalrpop-util = "0.18.1"
chrono = "0.4"
regex = "1"
lazy_static = "1.4.0"
rustyline = "5.0.3"
psutil = "1.0.0"
users = "0.9.1"
dirs = "1.0.5"
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
crossbeam = "0.7"
time = "0.1.40"
nix = "0.17.0"
prost = "0.6"
bytes = "0.5.4"
