[package]
name = "signature"
version = "0.1.0"
authors = ["Axel Liljencrantz <liljencranz@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.18"
quote = "1.0.3"
proc-macro2 = "1.0.10"
maplit = "1.0.2"


